const $ = (s) => document.querySelector(s);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let boot = {}, me = null, view = 'schoolai', cache = {classes:[], quizzes:[], members:[], reports:[]};

async function api(path, body) {
  return window.localApi(path, body);
}
function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2400); }
function backendUnavailable(message) { $('#app').innerHTML=`<div class="auth-screen"><section class="auth-art"><div class="brand"><span class="brand-mark">✦</span>Study<span>PLUS</span></div><h1>StudyPLUS could not start</h1><p>Refresh the page or open it again in a modern browser.</p></section><section class="auth-form-side"><div class="auth-box"><h2>Could not open local SQLite</h2><p>${esc(message)}</p><p>StudyPLUS saves its demo data in this browser.</p></div></section></div>`; }
async function start() {
  try { boot=await api('/bootstrap'); if (boot.me) { me=boot.me; await loadView(); } else authPage(); }
  catch(err) { backendUnavailable(err.message); }
}
function authPage(mode='login') {
  const setup=!boot.owner_exists && mode==='login';
  $('#app').innerHTML=`<div class="auth-screen"><section class="auth-art"><div class="brand"><span class="brand-mark">✦</span>Study<span>PLUS</span></div><h1>Learn a new language.<br>Meet the world.</h1><p>Join live online sessions, learn from teachers, and practice languages with a global community.</p></section><section class="auth-form-side"><div class="auth-box"><div class="brand"><span class="brand-mark">✦</span>Study<span>PLUS</span></div><h2>${setup?'Set up the owner account':mode==='login'?'Welcome back':'Join StudyPLUS'}</h2><p>${setup?'Create the first owner password to set up this browser.':mode==='login'?'Sign in to continue learning.':'Create your learner account. No verification code required.'}</p><form id="authForm"><label class="field">Email<input name="email" type="email" required value="${setup?esc(boot.owner_email):''}" placeholder="you@example.com" autocomplete="email"></label><label class="field">Password<input name="password" type="password" required minlength="${setup?10:8}" placeholder="${setup?'At least 10 characters':'At least 8 characters'}" autocomplete="${mode==='login'?'current-password':'new-password'}"></label>${mode==='register'?'<label class="field">Learning language<input name="language" placeholder="English, Arabic, French, Python…"></label>':''}<button class="primary" type="submit">${setup?'Create owner account':mode==='login'?'Sign in':'Create account'}</button></form>${!setup?`<div class="auth-switch">${mode==='login'?'New to StudyPLUS?':'Already joined?'} <button class="link" id="switch">${mode==='login'?'Create an account':'Sign in'}</button></div>`:''}<div class="role-welcome">Browser demo: accounts and saved data stay on this device only.</div></div></section></div>`;
  $('#switch')?.addEventListener('click',()=>authPage(mode==='login'?'register':'login'));
  $('#authForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),p={email:f.get('email'),password:f.get('password')};if(mode==='register')p.language=f.get('language');try{if(setup){await api('/owner/setup',p);boot.owner_exists=true;toast('Owner account created. Sign in to continue.');authPage('login');}else if(mode==='register'){await api('/register',p);toast('Account created. Sign in to start learning.');authPage('login');}else{await api('/login',p);boot=await api('/bootstrap');me=boot.me;await loadView();}}catch(err){toast(err.message);}};
}
async function loadView() {
  try {
    cache.classes=(await api('/classes')).classes||[];
    cache.quizzes=(await api('/quizzes')).quizzes||[];
    if(['owner','admin','helper','teacher'].includes(me.role)) cache.members=(await api('/members')).members||[];
    if(['owner','admin','helper'].includes(me.role)) cache.reports=(await api('/reports')).reports||[];
    render();
  } catch(err) {
    if(/updated|updating|temporarily/i.test(err.message)) $('#app').innerHTML='<div class="empty" style="margin:30vh auto;font-size:16px">We are fixing StudyPLUS. Please join later.</div>';
    else if(/banned/i.test(err.message)) $('#app').innerHTML='<div class="empty" style="margin:30vh auto;font-size:16px">You are banned from StudyPLUS.<br><small>Contact the owner if you think this is a mistake.</small></div>';
    else toast(err.message);
  }
}
function navItems() {
  const a=[['schoolai','✧','School AI'],['programming','⌘','Programming Class'],['discover','◉','Language sessions'],['sessions','◷','My sessions']];
  if(['teacher','owner'].includes(me.role)) a.push(['teacher','＋','Teacher panel']);
  if(['admin','helper','owner'].includes(me.role)) a.push(['members','♙','Members'],['reports','⚑','Reports']);
  if(me.role==='owner') a.push(['owner','⚙','Owner panel']);
  return a;
}
function render() {
  const title={schoolai:'School AI',programming:'Programming Class',discover:'Language sessions',sessions:'My sessions',teacher:'Teacher panel',members:'Members',reports:'Reports',owner:'Owner panel'}[view]||'Discover sessions';
  const page=view==='schoolai'?schoolAiView():view==='programming'?programmingView():view==='discover'?discover():view==='sessions'?mySessions():view==='teacher'?teacherView():view==='members'?membersView():view==='reports'?reportsView():ownerView();
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="brand-mark">✦</span>Study<span>PLUS</span></div><div class="profile"><div class="avatar">${esc(me.email[0].toUpperCase())}</div><div><b>${esc(me.email.split('@')[0])}</b><small><span class="badge ${esc(me.role)}">${esc(me.role)}</span></small></div></div><p class="nav-caption">LEARN</p>${navItems().map(([id,ico,label])=>`<button class="nav ${view===id?'active':''}" data-view="${id}"><span>${ico}</span>${label}</button>`).join('')}<div class="sidefoot">STUDYPLUS · LEARN TOGETHER</div></aside><main class="main"><header class="top"><div><p class="eyebrow">YOUR LEARNING SPACE</p><h1>${title}</h1><p class="subline">${esc(me.email)} · ${esc(me.role)}</p></div><button class="soft" id="logout">Sign out</button></header><div class="maintenance">Browser demo: accounts and data are saved on this device only.</div>${page}</main></div>`;
}
function schoolAiView(){return `<section class="hero"><h2>Ask School AI</h2><p>Search the web for school topics, explanations, and reliable sources.</p><form id="schoolSearch" class="search-form"><input name="query" required placeholder="Ask a question or search a topic…"><button class="primary">Search Google ↗</button></form><div id="schoolResults"></div></section><section class="panel"><div class="panel-head"><h2>How School AI works</h2><span class="pill">Google Search</span></div><p class="subline">Your search opens Google results in a new tab.</p></section>`;}
function programmingView(){const canCreate=['teacher','admin','owner'].includes(me.role);return `<section class="hero"><h2>Programming Class</h2><p>Learn coding through short quizzes. Teachers, admins, and the owner can create quizzes; every member can take them.</p>${canCreate?'<button class="primary" id="newQuiz">＋ Create quiz</button>':''}</section><h2 class="section-title">Quizzes <span class="pill">${cache.quizzes.length}</span></h2><div class="cards">${cache.quizzes.map(q=>`<article class="card class-card"><span class="lang-tag">${esc(q.language)} · ${q.question_count} questions</span><h3>${esc(q.title)}</h3><p>${esc(q.description||'Test your programming knowledge.')}</p><div class="card-foot"><span class="class-meta">${q.best_score===null?'Not attempted yet':`Best score: ${q.best_score}%`}</span><button class="primary" data-quiz="${q.id}">Take quiz</button></div></article>`).join('')||'<div class="empty">No quizzes yet. A teacher or admin can create one.</div>'}</div>`;}
function classCard(c) {
  const action=c.joined&&c.meeting_url?`<a class="soft" href="${esc(c.meeting_url)}" target="_blank" rel="noopener noreferrer">Open meeting ↗</a>`:`<button class="${c.joined?'soft':'primary'}" data-join="${c.id}">${c.joined?'Joined':'Join session'}</button>`;
  return `<article class="card class-card"><span class="lang-tag">${esc(c.language)} · ${esc(c.level)}</span><h3>${esc(c.title)}</h3><p>${esc(c.description||'Join this interactive online session.')}</p><div class="class-meta"><span>◷ ${esc(new Date(c.starts_at).toLocaleString())}</span><span>${c.duration} min</span></div><div class="card-foot"><span class="class-meta">${c.teacher_email?'Teacher: '+esc(c.teacher_email.split('@')[0]):'Teacher led'}</span>${action}</div></article>`;
}
function discover() { return `<section class="hero"><h2>Open a door to a new language</h2><p>Join live online sessions with teachers and learners. Practice speaking, explore new cultures, and learn at your pace.</p><button class="primary" onclick="document.querySelector('.section-title').scrollIntoView({behavior:'smooth'})">Explore sessions ↓</button></section><h2 class="section-title">Upcoming online sessions <span class="pill">${cache.classes.length} sessions</span></h2><div class="cards">${cache.classes.map(classCard).join('')||'<div class="empty">No sessions are scheduled yet.</div>'}</div>`; }
function mySessions() { const list=cache.classes.filter(c=>c.joined); return `<h2 class="section-title">Sessions you joined</h2><div class="cards">${list.map(classCard).join('')||'<div class="panel empty">You have not joined a session yet. Visit Discover to find one.</div>'}</div>`; }
function teacherView() { return `<section class="panel"><div class="panel-head"><h2>Schedule an online session</h2><span class="pill">Teacher tools</span></div><p class="subline">Create a language class for learners to discover and join.</p><button class="primary" id="createSession" style="margin-top:14px">＋ Create session</button></section><h2 class="section-title">Your sessions</h2><div class="cards">${cache.classes.filter(c=>c.teacher_id===me.id).map(classCard).join('')||'<div class="panel empty">You have not scheduled any sessions.</div>'}</div><section class="panel"><div class="panel-head"><h2>Report a member</h2><span class="pill">Reports go to staff for review</span></div><button class="soft" data-ban="report">＋ Submit a report</button></section>`; }
function membersView() {
  return `<section class="panel"><div class="panel-head"><h2>Community members</h2><span class="pill">${cache.members.length} accounts</span></div><div class="table-wrap"><table><thead><tr><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>JOINED</th>${['owner','admin'].includes(me.role)?'<th>ACTION</th>':''}</tr></thead><tbody>${cache.members.map(m=>`<tr><td>${esc(m.email)}</td><td>${me.role==='owner'&&m.role!=='owner'?`<select data-role data-id="${m.id}">${['student','teacher','helper','admin'].map(r=>`<option ${r===m.role?'selected':''}>${r}</option>`).join('')}</select>`:`<span class="badge ${esc(m.role)}">${esc(m.role)}</span>`}</td><td>${esc(m.status)}</td><td>${esc(m.created_at)}</td>${['owner','admin'].includes(me.role)?`<td>${m.role!=='owner'?(me.role==='owner'?(m.status==='banned'?`<button class="soft" data-unban="${m.id}">Unban</button>`:`<button class="danger" data-ban="${m.id}">Ban</button>`):`<button class="soft" data-ban="${m.id}">Request ban</button>`):''}</td>`:''}</tr>`).join('')}</tbody></table></div></section>`;
}
function reportsView() {
  return `<section class="panel"><div class="panel-head"><h2>Reports & ban requests</h2><span class="pill">Owner review required for bans</span></div>${cache.reports.map(r=>`<div class="report-row"><div class="grow"><b>${esc(r.reporter_email||'Former member')}</b> → <b>${esc(r.target_email||'Unknown member')}</b><br><span class="subline">${esc(r.reason)} · ${esc(r.status)}</span></div>${me.role==='owner'&&r.status==='pending'&&r.reason.startsWith('BAN REQUEST:')?`<div class="actions"><button class="primary" data-decision="approve" data-id="${r.id}">Approve ban</button><button class="soft" data-decision="decline" data-id="${r.id}">Decline</button></div>`:''}</div>`).join('')||'<div class="empty">No reports yet.</div>'}</section>`;
}
function ownerView() {
  return `<section class="panel"><div class="panel-head"><h2>Owner controls</h2><span class="pill">Owner only</span></div><label style="display:flex;align-items:center;gap:10px;font-size:12px"><input id="maintenanceToggle" type="checkbox" ${boot.maintenance?'checked':''} style="width:auto"> Enable maintenance mode</label><p class="subline">Learners and staff will see “We are updating StudyPLUS. Please come back later.” The owner can still sign in and manage the app.</p></section><section class="panel"><div class="panel-head"><h2>Owner account</h2></div><p class="subline">${esc(me.email)}. Review member reports in the Reports panel.</p><button class="soft" data-view="members">Manage members →</button></section>`;
}
function modal(html) { const d=$('#dialog');d.innerHTML=`<div class="dialog-inner">${html}</div>`;d.showModal();d.onclick=e=>{if(e.target===d)d.close();}; }
let questionNumber=0;
function questionEditor(){questionNumber++;return `<fieldset class="question-block"><legend>Question ${questionNumber}</legend><label class="field">Question<input name="prompt" required placeholder="Write a question"></label><div class="choice-grid">${[0,1,2,3].map((n)=>`<label class="field">Choice ${String.fromCharCode(65+n)}<input name="choice${n}" required></label>`).join('')}</div><label class="field">Correct answer<select name="answer_index"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></label></fieldset>`;}
function quizCreateDialog(){questionNumber=0;modal(`<h2>Create a programming quiz</h2><p>Add questions and select the correct answer for each one.</p><form id="quizForm"><label class="field">Quiz title<input name="title" required placeholder="JavaScript basics"></label><label class="field">Programming language<input name="language" value="Programming" required></label><label class="field">Description<input name="description" placeholder="What will learners practice?"></label><div id="questionEditors">${questionEditor()}</div><button type="button" class="soft" id="addQuestion">＋ Add question</button><div class="dialog-actions"><button type="button" class="soft" onclick="document.querySelector('dialog').close()">Cancel</button><button class="primary">Publish quiz</button></div></form>`);$('#quizForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),questions=[...document.querySelectorAll('.question-block')].map(row=>{const v=new FormData();return {prompt:row.querySelector('[name=prompt]').value,choices:[0,1,2,3].map(i=>row.querySelector(`[name=choice${i}]`).value),answer_index:Number(row.querySelector('[name=answer_index]').value)}});try{await api('/quizzes',{title:f.get('title'),language:f.get('language'),description:f.get('description'),questions});$('#dialog').close();toast('Quiz published');view='programming';await loadView();}catch(err){toast(err.message);}};$('#addQuestion').onclick=()=>$('#questionEditors').insertAdjacentHTML('beforeend',questionEditor());}
async function takeQuiz(id){try{const {quiz,questions}=await api(`/quizzes/${id}`);modal(`<h2>${esc(quiz.title)}</h2><p>${esc(quiz.description||'Choose one answer for each question.')}</p><form id="takeQuizForm">${questions.map((q,n)=>`<fieldset class="question-block"><legend>${n+1}. ${esc(q.prompt)}</legend>${q.choices.map((choice,i)=>`<label class="quiz-choice"><input type="radio" name="q${q.id}" value="${i}" required> ${esc(choice)}</label>`).join('')}</fieldset>`).join('')}<div class="dialog-actions"><button type="button" class="soft" onclick="document.querySelector('dialog').close()">Cancel</button><button class="primary">Submit answers</button></div></form>`);$('#takeQuizForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),answers={};for(const q of questions)answers[q.id]=f.get(`q${q.id}`);try{const result=await api(`/quizzes/${id}/submit`,{answers});$('#dialog').close();toast(`Score: ${result.score} / ${result.total} (${result.percent}%)`);await loadView();}catch(err){toast(err.message);}};}catch(err){toast(err.message);}}
function sessionDialog() {
  modal(`<h2>Schedule an online session</h2><p>Choose the language and time for your class.</p><form id="sessionForm"><label class="field">Session title<input name="title" required placeholder="Conversation practice"></label><label class="field">Language<input name="language" required placeholder="English, Arabic, French, Python…"></label><label class="field">Level<select name="level"><option>All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label class="field">Start time<input name="starts_at" type="datetime-local" required></label><label class="field">Duration (minutes)<input name="duration" type="number" min="15" max="240" value="60"></label><label class="field">Secure meeting link (https)<input name="meeting_url" type="url" placeholder="https://…"></label><label class="field">Description<textarea name="description" rows="3"></textarea></label><div class="dialog-actions"><button type="button" class="soft" onclick="document.querySelector('dialog').close()">Cancel</button><button class="primary">Create session</button></div></form>`);
  $('#sessionForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.duration=Number(p.duration);try{await api('/classes',p);$('#dialog').close();toast('Session scheduled');view='teacher';await loadView();}catch(err){toast(err.message);}};
}
function banDialog(id) {
  const direct=me.role==='owner'&&id!=='report';
  const members=cache.members.filter(m=>m.role!=='owner').map(m=>`<option value="${m.id}">${esc(m.email)}</option>`).join('');
  modal(`<h2>${id==='report'?'Report a member':direct?'Ban member':'Request a ban'}</h2><p>${direct?'Add a reason to ban this member.':'Explain what happened. The owner reviews requests before a ban takes effect.'}</p><form id="reportForm">${id==='report'?`<label class="field">Member<select name="target_id" required>${members}</select></label>`:''}<label class="field">Reason<textarea name="reason" required rows="4" placeholder="Describe the concern…"></textarea></label><div class="dialog-actions"><button type="button" class="soft" onclick="document.querySelector('dialog').close()">Cancel</button><button class="primary">${direct?'Confirm ban':'Send report'}</button></div></form>`);
  $('#reportForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),reason=f.get('reason');try{if(id==='report')await api('/reports',{target_id:f.get('target_id'),reason});else if(direct)await api(`/members/${id}/ban`,{reason});else await api(`/members/${id}/ban-request`,{reason});$('#dialog').close();toast(direct?'Member banned':'Report sent for review');await loadView();}catch(err){toast(err.message);}};
}
document.addEventListener('click',async e=>{
  const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;render();return;}
  if(e.target.closest('#logout')){await api('/logout',{});me=null;boot=await api('/bootstrap');authPage();return;}
  const join=e.target.closest('[data-join]');if(join){try{await api(`/classes/${join.dataset.join}/join`,{});toast('You joined this online session');await loadView();}catch(err){toast(err.message);}return;}
  if(e.target.closest('#createSession')){sessionDialog();return;}
  if(e.target.closest('#newQuiz')){quizCreateDialog();return;}
  const take=e.target.closest('[data-quiz]');if(take){await takeQuiz(take.dataset.quiz);return;}
  const ban=e.target.closest('[data-ban]');if(ban){banDialog(ban.dataset.ban);return;}
  const unban=e.target.closest('[data-unban]');if(unban){try{await api(`/members/${unban.dataset.unban}/unban`,{});toast('Member unbanned');await loadView();}catch(err){toast(err.message);}return;}
  const decision=e.target.closest('[data-decision]');if(decision){try{await api(`/reports/${decision.dataset.id}/decision`,{decision:decision.dataset.decision});toast('Request reviewed');await loadView();}catch(err){toast(err.message);}}
});
document.addEventListener('submit',e=>{
  if(e.target.id==='schoolSearch'){e.preventDefault();const query=new FormData(e.target).get('query').trim();if(!query)return;window.open(`https://www.google.com/search?q=${encodeURIComponent(query)}`,'_blank','noopener');$('#schoolResults').innerHTML=`<div class="role-welcome">Google results opened for: <b>${esc(query)}</b>. AI summaries can be enabled after configuring an AI service key.</div>`;}
});
document.addEventListener('change',async e=>{
  if(e.target.matches('[data-role]')){try{await api(`/members/${e.target.dataset.id}/role`,{role:e.target.value});toast('Member role updated');await loadView();}catch(err){toast(err.message);await loadView();}}
  if(e.target.id==='maintenanceToggle'){try{await api('/maintenance',{enabled:e.target.checked});boot.maintenance=e.target.checked;toast(e.target.checked?'Maintenance mode is on':'Maintenance mode is off');}catch(err){toast(err.message);}}
});
start();
