// StudyPLUS browser edition: SQLite compiled to WebAssembly, persisted in IndexedDB.
(() => {
  let db, userId = Number(localStorage.getItem('sp-user') || 0);
  const sql = (query, params=[]) => {
    const s=db.prepare(query); try { s.bind(params); const out=[]; while(s.step()) out.push(s.getAsObject()); return out; } finally { s.free(); }
  };
  const run=(query,params=[])=>{db.run(query,params);return db.exec('SELECT last_insert_rowid() AS id')[0]?.values[0][0]||0;};
  const one=(query,params=[])=>sql(query,params)[0]||null;
  function persist(){const bytes=db.export();return new Promise((resolve,reject)=>{const req=indexedDB.open('studyplus-sqlite-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction('data','readwrite');tx.objectStore('data').put(bytes,'db');tx.oncomplete=()=>{req.result.close();resolve();};tx.onerror=()=>reject(tx.error);};});}
  function load(){return new Promise((resolve,reject)=>{const req=indexedDB.open('studyplus-sqlite-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const r=req.result.transaction('data').objectStore('data').get('db');r.onsuccess=()=>{resolve(r.result);req.result.close();};r.onerror=()=>reject(r.error);};});}
  async function digest(password,salt){const data=new TextEncoder().encode(`${salt}:${password}`);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  async function openDb(){const SQL=await initSqlJs({locateFile:f=>'./vendor/'+f});const saved=await load();db=saved?new SQL.Database(new Uint8Array(saved)):new SQL.Database();db.run(`PRAGMA foreign_keys=ON;
    CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'student',status TEXT NOT NULL DEFAULT 'active',learning_language TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS classes(id INTEGER PRIMARY KEY,title TEXT NOT NULL,language TEXT NOT NULL,level TEXT NOT NULL DEFAULT 'All levels',starts_at TEXT NOT NULL,duration INTEGER NOT NULL DEFAULT 60,teacher_id INTEGER,description TEXT NOT NULL DEFAULT '',meeting_url TEXT NOT NULL DEFAULT '');
    CREATE TABLE IF NOT EXISTS class_joins(class_id INTEGER,user_id INTEGER,PRIMARY KEY(class_id,user_id));
    CREATE TABLE IF NOT EXISTS quizzes(id INTEGER PRIMARY KEY,title TEXT NOT NULL,language TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',author_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS quiz_questions(id INTEGER PRIMARY KEY,quiz_id INTEGER,prompt TEXT,choices TEXT,answer_index INTEGER);
    CREATE TABLE IF NOT EXISTS quiz_attempts(id INTEGER PRIMARY KEY,quiz_id INTEGER,user_id INTEGER,score INTEGER,total INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY,reporter_id INTEGER,target_id INTEGER,reason TEXT,status TEXT DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
    INSERT OR IGNORE INTO settings VALUES('owner_email','owner@example.com');INSERT OR IGNORE INTO settings VALUES('maintenance','0');
    INSERT OR IGNORE INTO settings VALUES('app_name','StudyPLUS');INSERT OR IGNORE INTO settings VALUES('tagline','Learn together');`);await persist();}
  const safe=u=>u&&({id:u.id,email:u.email,role:u.role,status:u.status,created_at:u.created_at,learning_language:u.learning_language});
  function requireUser(){const u=one('SELECT * FROM users WHERE id=?',[userId]);if(!u)throw Error('Sign in to continue.');if(u.status==='banned'&&u.role!=='owner')throw Error('Your account is banned. Contact the StudyPLUS owner for help.');if(one("SELECT value FROM settings WHERE key='maintenance'")?.value==='1'&&u.role!=='owner')throw Error('We are updating StudyPLUS. Please come back later.');return u;}
  const roles=['owner','admin','helper','teacher','student'];
  window.localApi=async(path,body)=>{if(!db)await openDb();const p=path.split('?')[0],method=!!body;
    if(!method&&p==='/bootstrap'){const owner=one("SELECT id FROM users WHERE role='owner'");const setting=k=>one('SELECT value FROM settings WHERE key=?',[k])?.value;return{owner_exists:!!owner,owner_email:setting('owner_email'),maintenance:setting('maintenance')==='1',app_name:setting('app_name'),tagline:setting('tagline'),me:safe(one('SELECT * FROM users WHERE id=?',[userId]))};}
    if(method&&p==='/owner/setup'){if(one("SELECT id FROM users WHERE role='owner'"))throw Error('Owner setup is already complete.');const email=String(body.email||'').trim().toLowerCase();if(!email.includes('@')||body.password.length<10)throw Error('Enter a valid email and a password of at least 10 characters.');const salt=crypto.randomUUID();run('INSERT INTO users(email,password_hash,role) VALUES(?,?,?)',[email,`${salt}:${await digest(body.password,salt)}`,'owner']);run("UPDATE settings SET value=? WHERE key='owner_email'",[email]);await persist();return{ok:true};}
    if(method&&p==='/register'){const email=String(body.email||'').trim().toLowerCase();if(!email.includes('@')||body.password.length<8)throw Error('Enter a valid email and a password with at least 8 characters.');if(one('SELECT id FROM users WHERE email=?',[email]))throw Error('That email already has an account.');const salt=crypto.randomUUID();run('INSERT INTO users(email,password_hash,learning_language) VALUES(?,?,?)',[email,`${salt}:${await digest(body.password,salt)}`,body.language||'']);await persist();return{ok:true};}
    if(method&&p==='/login'){const u=one('SELECT * FROM users WHERE email=?',[String(body.email).trim().toLowerCase()]);if(!u)throw Error('Email or password is incorrect.');const [salt,hash]=u.password_hash.split(':');if(await digest(body.password,salt)!==hash)throw Error('Email or password is incorrect.');if(u.status==='banned'&&u.role!=='owner')throw Error('Your account is banned. Contact the StudyPLUS owner for help.');userId=u.id;localStorage.setItem('sp-user',userId);return{ok:true,user:safe(u)};}
    if(method&&p==='/logout'){userId=0;localStorage.removeItem('sp-user');return{ok:true};}
    const me=requireUser();
    if(!method&&p==='/me')return{me:safe(me),maintenance:one("SELECT value FROM settings WHERE key='maintenance'").value==='1'};
    if(!method&&p==='/classes')return{classes:sql('SELECT c.*,u.email teacher_email,EXISTS(SELECT 1 FROM class_joins j WHERE j.class_id=c.id AND j.user_id=?) joined FROM classes c LEFT JOIN users u ON c.teacher_id=u.id ORDER BY starts_at',[me.id])};
    if(!method&&p==='/quizzes')return{quizzes:sql('SELECT q.id,q.title,q.language,q.description,q.created_at,u.email author_email,(SELECT COUNT(*) FROM quiz_questions x WHERE x.quiz_id=q.id) question_count,(SELECT MAX(CAST(a.score*100.0/NULLIF(a.total,0) AS INTEGER)) FROM quiz_attempts a WHERE a.quiz_id=q.id AND a.user_id=?) best_score FROM quizzes q LEFT JOIN users u ON u.id=q.author_id ORDER BY q.id DESC',[me.id])};
    if(!method&&p.startsWith('/quizzes/')){const id=Number(p.split('/')[2]),quiz=one('SELECT * FROM quizzes WHERE id=?',[id]);if(!quiz)throw Error('Quiz not found.');return{quiz,questions:sql('SELECT id,prompt,choices,answer_index FROM quiz_questions WHERE quiz_id=? ORDER BY id',[id]).map(q=>({...q,choices:JSON.parse(q.choices)}))};}
    if(!method&&p==='/members'){if(!['owner','admin','helper','teacher'].includes(me.role))throw Error('Not allowed.');return{members:sql('SELECT id,email,role,status,created_at,learning_language FROM users ORDER BY created_at DESC')};}
    if(!method&&p==='/reports'){if(!['owner','admin','helper'].includes(me.role))throw Error('Not allowed.');return{reports:sql('SELECT r.*,a.email reporter_email,b.email target_email FROM reports r LEFT JOIN users a ON a.id=r.reporter_id LEFT JOIN users b ON b.id=r.target_id ORDER BY r.id DESC')};}
    if(!method&&p==='/settings'){if(me.role!=='owner')throw Error('Owner access required.');return{app_name:one("SELECT value FROM settings WHERE key='app_name'").value,tagline:one("SELECT value FROM settings WHERE key='tagline'").value};}
    if(method&&p==='/settings'){if(me.role!=='owner')throw Error('Owner access required.');run("UPDATE settings SET value=? WHERE key='app_name'",[String(body.app_name||'StudyPLUS').trim().slice(0,40)]);run("UPDATE settings SET value=? WHERE key='tagline'",[String(body.tagline||'Learn together').trim().slice(0,100)]);await persist();return{ok:true};}
    if(method&&p==='/classes'){if(!['owner','teacher'].includes(me.role))throw Error('Teacher access required.');if(body.meeting_url&&!body.meeting_url.startsWith('https://'))throw Error('Use a secure https meeting link.');run('INSERT INTO classes(title,language,level,starts_at,duration,teacher_id,description,meeting_url) VALUES(?,?,?,?,?,?,?,?)',[body.title,body.language,body.level||'All levels',body.starts_at,Number(body.duration)||60,me.id,body.description||'',body.meeting_url||'']);}
    else if(method&&p.match(/^\/classes\/\d+\/edit$/)){if(me.role!=='owner'&&me.role!=='teacher')throw Error('Teacher access required.');const id=Number(p.split('/')[2]),current=one('SELECT * FROM classes WHERE id=?',[id]);if(!current||(me.role!=='owner'&&current.teacher_id!==me.id))throw Error('You can only edit your own sessions.');if(body.meeting_url&&!body.meeting_url.startsWith('https://'))throw Error('Use a secure https meeting link.');run('UPDATE classes SET title=?,language=?,level=?,starts_at=?,duration=?,description=?,meeting_url=? WHERE id=?',[body.title,body.language,body.level||'All levels',body.starts_at,Number(body.duration)||60,body.description||'',body.meeting_url||'',id]);}
    else if(method&&p.match(/^\/classes\/\d+\/delete$/)){if(me.role!=='owner')throw Error('Owner access required.');const id=Number(p.split('/')[2]);run('DELETE FROM class_joins WHERE class_id=?',[id]);run('DELETE FROM classes WHERE id=?',[id]);}
    else if(method&&p==='/quizzes'){if(!['teacher','admin','owner'].includes(me.role))throw Error('Only teachers, admins, and the owner can create quizzes.');if(!body.title||!body.questions?.length)throw Error('Add a quiz title and at least one question.');const id=run('INSERT INTO quizzes(title,language,description,author_id) VALUES(?,?,?,?)',[body.title,body.language,body.description||'',me.id]);for(const q of body.questions)run('INSERT INTO quiz_questions(quiz_id,prompt,choices,answer_index) VALUES(?,?,?,?)',[id,q.prompt,JSON.stringify(q.choices),q.answer_index]);}
    else if(method&&p.match(/^\/quizzes\/\d+\/edit$/)){if(me.role!=='owner'&&me.role!=='admin')throw Error('Owner or admin access required.');const id=Number(p.split('/')[2]);if(!one('SELECT id FROM quizzes WHERE id=?',[id]))throw Error('Quiz not found.');if(!body.title||!body.questions?.length)throw Error('Add a quiz title and at least one question.');run('UPDATE quizzes SET title=?,language=?,description=? WHERE id=?',[body.title,body.language,body.description||'',id]);run('DELETE FROM quiz_questions WHERE quiz_id=?',[id]);for(const q of body.questions)run('INSERT INTO quiz_questions(quiz_id,prompt,choices,answer_index) VALUES(?,?,?,?)',[id,q.prompt,JSON.stringify(q.choices),q.answer_index]);}
    else if(method&&p.match(/^\/quizzes\/\d+\/delete$/)){if(me.role!=='owner')throw Error('Owner access required.');const id=Number(p.split('/')[2]);run('DELETE FROM quiz_attempts WHERE quiz_id=?',[id]);run('DELETE FROM quiz_questions WHERE quiz_id=?',[id]);run('DELETE FROM quizzes WHERE id=?',[id]);}
    else if(method&&p.match(/^\/quizzes\/\d+\/submit$/)){const id=Number(p.split('/')[2]),qs=sql('SELECT id,answer_index FROM quiz_questions WHERE quiz_id=? ORDER BY id',[id]);if(!qs.length)throw Error('Quiz not found or has no questions.');const score=qs.filter(q=>String(body.answers[q.id])===String(q.answer_index)).length;run('INSERT INTO quiz_attempts(quiz_id,user_id,score,total) VALUES(?,?,?,?)',[id,me.id,score,qs.length]);await persist();return{score,total:qs.length,percent:Math.round(score*100/qs.length)};}
    else if(method&&p.match(/^\/classes\/\d+\/join$/)){run('INSERT OR IGNORE INTO class_joins(class_id,user_id) VALUES(?,?)',[Number(p.split('/')[2]),me.id]);}
    else if(method&&p==='/reports'){if(!['teacher','admin','helper','owner'].includes(me.role))throw Error('Teacher or staff access required.');run('INSERT INTO reports(reporter_id,target_id,reason) VALUES(?,?,?)',[me.id,Number(body.target_id),body.reason]);}
    else if(method&&p.match(/^\/members\/\d+\/role$/)){if(!['owner','admin'].includes(me.role))throw Error('Owner or admin access required.');const id=Number(p.split('/')[2]);if(!roles.includes(body.role)||body.role==='owner'||one('SELECT role FROM users WHERE id=?',[id])?.role==='owner')throw Error('That role change is not allowed.');run('UPDATE users SET role=? WHERE id=?',[body.role,id]);}
    else if(method&&p.match(/^\/members\/\d+\/ban$/)){if(me.role!=='owner')throw Error('Only the owner can ban a member.');const id=Number(p.split('/')[2]);run("UPDATE users SET status='banned' WHERE id=? AND role!='owner'",[id]);run("INSERT INTO reports(reporter_id,target_id,reason,status) VALUES(?,?,?,'approved')",[me.id,id,'OWNER BAN: '+body.reason]);}
    else if(method&&p.match(/^\/members\/\d+\/unban$/)){if(me.role!=='owner')throw Error('Only the owner can unban a member.');run("UPDATE users SET status='active' WHERE id=? AND role!='owner'",[Number(p.split('/')[2])]);}
    else if(method&&p.match(/^\/members\/\d+\/ban-request$/)){if(!['teacher','admin','helper'].includes(me.role))throw Error('Teacher or staff access required.');run('INSERT INTO reports(reporter_id,target_id,reason) VALUES(?,?,?)',[me.id,Number(p.split('/')[2]),'BAN REQUEST: '+body.reason]);}
    else if(method&&p.match(/^\/reports\/\d+\/decision$/)){if(me.role!=='owner')throw Error('Only the owner can approve ban requests.');const id=Number(p.split('/')[2]),report=one('SELECT * FROM reports WHERE id=?',[id]);if(!report||!['approve','decline'].includes(body.decision))throw Error('Invalid decision.');run('UPDATE reports SET status=? WHERE id=?',[body.decision==='approve'?'approved':'declined',id]);if(body.decision==='approve'&&report.reason.startsWith('BAN REQUEST:'))run("UPDATE users SET status='banned' WHERE id=? AND role!='owner'",[report.target_id]);}
    else if(method&&p==='/maintenance'){if(me.role!=='owner')throw Error('Owner access required.');run("UPDATE settings SET value=? WHERE key='maintenance'",[body.enabled?'1':'0']);}
    else throw Error('Not found.');
    await persist();return{ok:true};
  };
})();
